/*
 * Generated by gdbus-codegen 2.56.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "grl-dleyna-proxy-manager.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.intel.dLeynaServer.Manager
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:GrlDleynaManager
 * @title: GrlDleynaManager
 * @short_description: Generated C code for the com.intel.dLeynaServer.Manager D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-intel-dLeynaServer-Manager.top_of_page">com.intel.dLeynaServer.Manager</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.intel.dLeynaServer.Manager ---- */

static const _ExtendedGDBusArgInfo _grl_dleyna_manager_method_info_get_version_OUT_ARG_Version =
{
  {
    -1,
    (gchar *) "Version",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _grl_dleyna_manager_method_info_get_version_OUT_ARG_pointers[] =
{
  &_grl_dleyna_manager_method_info_get_version_OUT_ARG_Version,
  NULL
};

static const _ExtendedGDBusMethodInfo _grl_dleyna_manager_method_info_get_version =
{
  {
    -1,
    (gchar *) "GetVersion",
    NULL,
    (GDBusArgInfo **) &_grl_dleyna_manager_method_info_get_version_OUT_ARG_pointers,
    NULL
  },
  "handle-get-version",
  FALSE
};

static const _ExtendedGDBusMethodInfo _grl_dleyna_manager_method_info_release =
{
  {
    -1,
    (gchar *) "Release",
    NULL,
    NULL,
    NULL
  },
  "handle-release",
  FALSE
};

static const _ExtendedGDBusArgInfo _grl_dleyna_manager_method_info_get_servers_OUT_ARG_Servers =
{
  {
    -1,
    (gchar *) "Servers",
    (gchar *) "ao",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _grl_dleyna_manager_method_info_get_servers_OUT_ARG_pointers[] =
{
  &_grl_dleyna_manager_method_info_get_servers_OUT_ARG_Servers,
  NULL
};

static const _ExtendedGDBusMethodInfo _grl_dleyna_manager_method_info_get_servers =
{
  {
    -1,
    (gchar *) "GetServers",
    NULL,
    (GDBusArgInfo **) &_grl_dleyna_manager_method_info_get_servers_OUT_ARG_pointers,
    NULL
  },
  "handle-get-servers",
  FALSE
};

static const _ExtendedGDBusMethodInfo _grl_dleyna_manager_method_info_rescan =
{
  {
    -1,
    (gchar *) "Rescan",
    NULL,
    NULL,
    NULL
  },
  "handle-rescan",
  FALSE
};

static const _ExtendedGDBusArgInfo _grl_dleyna_manager_method_info_set_protocol_info_IN_ARG_ProtocolInfo =
{
  {
    -1,
    (gchar *) "ProtocolInfo",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _grl_dleyna_manager_method_info_set_protocol_info_IN_ARG_pointers[] =
{
  &_grl_dleyna_manager_method_info_set_protocol_info_IN_ARG_ProtocolInfo,
  NULL
};

static const _ExtendedGDBusMethodInfo _grl_dleyna_manager_method_info_set_protocol_info =
{
  {
    -1,
    (gchar *) "SetProtocolInfo",
    (GDBusArgInfo **) &_grl_dleyna_manager_method_info_set_protocol_info_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-protocol-info",
  FALSE
};

static const _ExtendedGDBusArgInfo _grl_dleyna_manager_method_info_prefer_local_addresses_IN_ARG_Prefer =
{
  {
    -1,
    (gchar *) "Prefer",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _grl_dleyna_manager_method_info_prefer_local_addresses_IN_ARG_pointers[] =
{
  &_grl_dleyna_manager_method_info_prefer_local_addresses_IN_ARG_Prefer,
  NULL
};

static const _ExtendedGDBusMethodInfo _grl_dleyna_manager_method_info_prefer_local_addresses =
{
  {
    -1,
    (gchar *) "PreferLocalAddresses",
    (GDBusArgInfo **) &_grl_dleyna_manager_method_info_prefer_local_addresses_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-prefer-local-addresses",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _grl_dleyna_manager_method_info_pointers[] =
{
  &_grl_dleyna_manager_method_info_get_version,
  &_grl_dleyna_manager_method_info_release,
  &_grl_dleyna_manager_method_info_get_servers,
  &_grl_dleyna_manager_method_info_rescan,
  &_grl_dleyna_manager_method_info_set_protocol_info,
  &_grl_dleyna_manager_method_info_prefer_local_addresses,
  NULL
};

static const _ExtendedGDBusArgInfo _grl_dleyna_manager_signal_info_found_server_ARG_Path =
{
  {
    -1,
    (gchar *) "Path",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _grl_dleyna_manager_signal_info_found_server_ARG_pointers[] =
{
  &_grl_dleyna_manager_signal_info_found_server_ARG_Path,
  NULL
};

static const _ExtendedGDBusSignalInfo _grl_dleyna_manager_signal_info_found_server =
{
  {
    -1,
    (gchar *) "FoundServer",
    (GDBusArgInfo **) &_grl_dleyna_manager_signal_info_found_server_ARG_pointers,
    NULL
  },
  "found-server"
};

static const _ExtendedGDBusArgInfo _grl_dleyna_manager_signal_info_lost_server_ARG_Path =
{
  {
    -1,
    (gchar *) "Path",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _grl_dleyna_manager_signal_info_lost_server_ARG_pointers[] =
{
  &_grl_dleyna_manager_signal_info_lost_server_ARG_Path,
  NULL
};

static const _ExtendedGDBusSignalInfo _grl_dleyna_manager_signal_info_lost_server =
{
  {
    -1,
    (gchar *) "LostServer",
    (GDBusArgInfo **) &_grl_dleyna_manager_signal_info_lost_server_ARG_pointers,
    NULL
  },
  "lost-server"
};

static const _ExtendedGDBusSignalInfo * const _grl_dleyna_manager_signal_info_pointers[] =
{
  &_grl_dleyna_manager_signal_info_found_server,
  &_grl_dleyna_manager_signal_info_lost_server,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _grl_dleyna_manager_interface_info =
{
  {
    -1,
    (gchar *) "com.intel.dLeynaServer.Manager",
    (GDBusMethodInfo **) &_grl_dleyna_manager_method_info_pointers,
    (GDBusSignalInfo **) &_grl_dleyna_manager_signal_info_pointers,
    NULL,
    NULL
  },
  "manager",
};


/**
 * grl_dleyna_manager_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-intel-dLeynaServer-Manager.top_of_page">com.intel.dLeynaServer.Manager</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
grl_dleyna_manager_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_grl_dleyna_manager_interface_info.parent_struct;
}

/**
 * grl_dleyna_manager_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #GrlDleynaManager interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
grl_dleyna_manager_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * GrlDleynaManager:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-intel-dLeynaServer-Manager.top_of_page">com.intel.dLeynaServer.Manager</link>.
 */

/**
 * GrlDleynaManagerIface:
 * @parent_iface: The parent interface.
 * @handle_get_servers: Handler for the #GrlDleynaManager::handle-get-servers signal.
 * @handle_get_version: Handler for the #GrlDleynaManager::handle-get-version signal.
 * @handle_prefer_local_addresses: Handler for the #GrlDleynaManager::handle-prefer-local-addresses signal.
 * @handle_release: Handler for the #GrlDleynaManager::handle-release signal.
 * @handle_rescan: Handler for the #GrlDleynaManager::handle-rescan signal.
 * @handle_set_protocol_info: Handler for the #GrlDleynaManager::handle-set-protocol-info signal.
 * @found_server: Handler for the #GrlDleynaManager::found-server signal.
 * @lost_server: Handler for the #GrlDleynaManager::lost-server signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-intel-dLeynaServer-Manager.top_of_page">com.intel.dLeynaServer.Manager</link>.
 */

typedef GrlDleynaManagerIface GrlDleynaManagerInterface;
G_DEFINE_INTERFACE (GrlDleynaManager, grl_dleyna_manager, G_TYPE_OBJECT)

static void
grl_dleyna_manager_default_init (GrlDleynaManagerIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * GrlDleynaManager::handle-get-version:
   * @object: A #GrlDleynaManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.GetVersion">GetVersion()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call grl_dleyna_manager_complete_get_version() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-version",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GrlDleynaManagerIface, handle_get_version),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * GrlDleynaManager::handle-release:
   * @object: A #GrlDleynaManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.Release">Release()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call grl_dleyna_manager_complete_release() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-release",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GrlDleynaManagerIface, handle_release),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * GrlDleynaManager::handle-get-servers:
   * @object: A #GrlDleynaManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.GetServers">GetServers()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call grl_dleyna_manager_complete_get_servers() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-servers",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GrlDleynaManagerIface, handle_get_servers),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * GrlDleynaManager::handle-rescan:
   * @object: A #GrlDleynaManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.Rescan">Rescan()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call grl_dleyna_manager_complete_rescan() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-rescan",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GrlDleynaManagerIface, handle_rescan),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * GrlDleynaManager::handle-set-protocol-info:
   * @object: A #GrlDleynaManager.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_ProtocolInfo: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.SetProtocolInfo">SetProtocolInfo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call grl_dleyna_manager_complete_set_protocol_info() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-protocol-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GrlDleynaManagerIface, handle_set_protocol_info),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * GrlDleynaManager::handle-prefer-local-addresses:
   * @object: A #GrlDleynaManager.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_Prefer: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.PreferLocalAddresses">PreferLocalAddresses()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call grl_dleyna_manager_complete_prefer_local_addresses() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-prefer-local-addresses",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GrlDleynaManagerIface, handle_prefer_local_addresses),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_BOOLEAN);

  /* GObject signals for received D-Bus signals: */
  /**
   * GrlDleynaManager::found-server:
   * @object: A #GrlDleynaManager.
   * @arg_Path: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-intel-dLeynaServer-Manager.FoundServer">"FoundServer"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("found-server",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GrlDleynaManagerIface, found_server),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * GrlDleynaManager::lost-server:
   * @object: A #GrlDleynaManager.
   * @arg_Path: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-com-intel-dLeynaServer-Manager.LostServer">"LostServer"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("lost-server",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GrlDleynaManagerIface, lost_server),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

}

/**
 * grl_dleyna_manager_emit_found_server:
 * @object: A #GrlDleynaManager.
 * @arg_Path: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-intel-dLeynaServer-Manager.FoundServer">"FoundServer"</link> D-Bus signal.
 */
void
grl_dleyna_manager_emit_found_server (
    GrlDleynaManager *object,
    const gchar *arg_Path)
{
  g_signal_emit_by_name (object, "found-server", arg_Path);
}

/**
 * grl_dleyna_manager_emit_lost_server:
 * @object: A #GrlDleynaManager.
 * @arg_Path: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-com-intel-dLeynaServer-Manager.LostServer">"LostServer"</link> D-Bus signal.
 */
void
grl_dleyna_manager_emit_lost_server (
    GrlDleynaManager *object,
    const gchar *arg_Path)
{
  g_signal_emit_by_name (object, "lost-server", arg_Path);
}

/**
 * grl_dleyna_manager_call_get_version:
 * @proxy: A #GrlDleynaManagerProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.GetVersion">GetVersion()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call grl_dleyna_manager_call_get_version_finish() to get the result of the operation.
 *
 * See grl_dleyna_manager_call_get_version_sync() for the synchronous, blocking version of this method.
 */
void
grl_dleyna_manager_call_get_version (
    GrlDleynaManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetVersion",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * grl_dleyna_manager_call_get_version_finish:
 * @proxy: A #GrlDleynaManagerProxy.
 * @out_Version: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to grl_dleyna_manager_call_get_version().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with grl_dleyna_manager_call_get_version().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_get_version_finish (
    GrlDleynaManager *proxy,
    gchar **out_Version,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_Version);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_get_version_sync:
 * @proxy: A #GrlDleynaManagerProxy.
 * @out_Version: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.GetVersion">GetVersion()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See grl_dleyna_manager_call_get_version() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_get_version_sync (
    GrlDleynaManager *proxy,
    gchar **out_Version,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetVersion",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_Version);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_release:
 * @proxy: A #GrlDleynaManagerProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.Release">Release()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call grl_dleyna_manager_call_release_finish() to get the result of the operation.
 *
 * See grl_dleyna_manager_call_release_sync() for the synchronous, blocking version of this method.
 */
void
grl_dleyna_manager_call_release (
    GrlDleynaManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Release",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * grl_dleyna_manager_call_release_finish:
 * @proxy: A #GrlDleynaManagerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to grl_dleyna_manager_call_release().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with grl_dleyna_manager_call_release().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_release_finish (
    GrlDleynaManager *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_release_sync:
 * @proxy: A #GrlDleynaManagerProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.Release">Release()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See grl_dleyna_manager_call_release() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_release_sync (
    GrlDleynaManager *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Release",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_get_servers:
 * @proxy: A #GrlDleynaManagerProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.GetServers">GetServers()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call grl_dleyna_manager_call_get_servers_finish() to get the result of the operation.
 *
 * See grl_dleyna_manager_call_get_servers_sync() for the synchronous, blocking version of this method.
 */
void
grl_dleyna_manager_call_get_servers (
    GrlDleynaManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetServers",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * grl_dleyna_manager_call_get_servers_finish:
 * @proxy: A #GrlDleynaManagerProxy.
 * @out_Servers: (out) (array zero-terminated=1): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to grl_dleyna_manager_call_get_servers().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with grl_dleyna_manager_call_get_servers().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_get_servers_finish (
    GrlDleynaManager *proxy,
    gchar ***out_Servers,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^ao)",
                 out_Servers);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_get_servers_sync:
 * @proxy: A #GrlDleynaManagerProxy.
 * @out_Servers: (out) (array zero-terminated=1): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.GetServers">GetServers()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See grl_dleyna_manager_call_get_servers() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_get_servers_sync (
    GrlDleynaManager *proxy,
    gchar ***out_Servers,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetServers",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^ao)",
                 out_Servers);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_rescan:
 * @proxy: A #GrlDleynaManagerProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.Rescan">Rescan()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call grl_dleyna_manager_call_rescan_finish() to get the result of the operation.
 *
 * See grl_dleyna_manager_call_rescan_sync() for the synchronous, blocking version of this method.
 */
void
grl_dleyna_manager_call_rescan (
    GrlDleynaManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Rescan",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * grl_dleyna_manager_call_rescan_finish:
 * @proxy: A #GrlDleynaManagerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to grl_dleyna_manager_call_rescan().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with grl_dleyna_manager_call_rescan().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_rescan_finish (
    GrlDleynaManager *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_rescan_sync:
 * @proxy: A #GrlDleynaManagerProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.Rescan">Rescan()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See grl_dleyna_manager_call_rescan() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_rescan_sync (
    GrlDleynaManager *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Rescan",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_set_protocol_info:
 * @proxy: A #GrlDleynaManagerProxy.
 * @arg_ProtocolInfo: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.SetProtocolInfo">SetProtocolInfo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call grl_dleyna_manager_call_set_protocol_info_finish() to get the result of the operation.
 *
 * See grl_dleyna_manager_call_set_protocol_info_sync() for the synchronous, blocking version of this method.
 */
void
grl_dleyna_manager_call_set_protocol_info (
    GrlDleynaManager *proxy,
    const gchar *arg_ProtocolInfo,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetProtocolInfo",
    g_variant_new ("(s)",
                   arg_ProtocolInfo),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * grl_dleyna_manager_call_set_protocol_info_finish:
 * @proxy: A #GrlDleynaManagerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to grl_dleyna_manager_call_set_protocol_info().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with grl_dleyna_manager_call_set_protocol_info().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_set_protocol_info_finish (
    GrlDleynaManager *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_set_protocol_info_sync:
 * @proxy: A #GrlDleynaManagerProxy.
 * @arg_ProtocolInfo: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.SetProtocolInfo">SetProtocolInfo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See grl_dleyna_manager_call_set_protocol_info() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_set_protocol_info_sync (
    GrlDleynaManager *proxy,
    const gchar *arg_ProtocolInfo,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetProtocolInfo",
    g_variant_new ("(s)",
                   arg_ProtocolInfo),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_prefer_local_addresses:
 * @proxy: A #GrlDleynaManagerProxy.
 * @arg_Prefer: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.PreferLocalAddresses">PreferLocalAddresses()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call grl_dleyna_manager_call_prefer_local_addresses_finish() to get the result of the operation.
 *
 * See grl_dleyna_manager_call_prefer_local_addresses_sync() for the synchronous, blocking version of this method.
 */
void
grl_dleyna_manager_call_prefer_local_addresses (
    GrlDleynaManager *proxy,
    gboolean arg_Prefer,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "PreferLocalAddresses",
    g_variant_new ("(b)",
                   arg_Prefer),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * grl_dleyna_manager_call_prefer_local_addresses_finish:
 * @proxy: A #GrlDleynaManagerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to grl_dleyna_manager_call_prefer_local_addresses().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with grl_dleyna_manager_call_prefer_local_addresses().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_prefer_local_addresses_finish (
    GrlDleynaManager *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_call_prefer_local_addresses_sync:
 * @proxy: A #GrlDleynaManagerProxy.
 * @arg_Prefer: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.PreferLocalAddresses">PreferLocalAddresses()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See grl_dleyna_manager_call_prefer_local_addresses() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
grl_dleyna_manager_call_prefer_local_addresses_sync (
    GrlDleynaManager *proxy,
    gboolean arg_Prefer,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "PreferLocalAddresses",
    g_variant_new ("(b)",
                   arg_Prefer),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * grl_dleyna_manager_complete_get_version:
 * @object: A #GrlDleynaManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @Version: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.GetVersion">GetVersion()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
grl_dleyna_manager_complete_get_version (
    GrlDleynaManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *Version)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   Version));
}

/**
 * grl_dleyna_manager_complete_release:
 * @object: A #GrlDleynaManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.Release">Release()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
grl_dleyna_manager_complete_release (
    GrlDleynaManager *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * grl_dleyna_manager_complete_get_servers:
 * @object: A #GrlDleynaManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @Servers: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.GetServers">GetServers()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
grl_dleyna_manager_complete_get_servers (
    GrlDleynaManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *Servers)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^ao)",
                   Servers));
}

/**
 * grl_dleyna_manager_complete_rescan:
 * @object: A #GrlDleynaManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.Rescan">Rescan()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
grl_dleyna_manager_complete_rescan (
    GrlDleynaManager *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * grl_dleyna_manager_complete_set_protocol_info:
 * @object: A #GrlDleynaManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.SetProtocolInfo">SetProtocolInfo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
grl_dleyna_manager_complete_set_protocol_info (
    GrlDleynaManager *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * grl_dleyna_manager_complete_prefer_local_addresses:
 * @object: A #GrlDleynaManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-intel-dLeynaServer-Manager.PreferLocalAddresses">PreferLocalAddresses()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
grl_dleyna_manager_complete_prefer_local_addresses (
    GrlDleynaManager *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * GrlDleynaManagerProxy:
 *
 * The #GrlDleynaManagerProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GrlDleynaManagerProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GrlDleynaManagerProxy.
 */

struct _GrlDleynaManagerProxyPrivate
{
  GData *qdata;
};

static void grl_dleyna_manager_proxy_iface_init (GrlDleynaManagerIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GrlDleynaManagerProxy, grl_dleyna_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (GrlDleynaManagerProxy)
                         G_IMPLEMENT_INTERFACE (GRL_DLEYNA_TYPE_MANAGER, grl_dleyna_manager_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (GrlDleynaManagerProxy, grl_dleyna_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GRL_DLEYNA_TYPE_MANAGER, grl_dleyna_manager_proxy_iface_init))

#endif
static void
grl_dleyna_manager_proxy_finalize (GObject *object)
{
  GrlDleynaManagerProxy *proxy = GRL_DLEYNA_MANAGER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (grl_dleyna_manager_proxy_parent_class)->finalize (object);
}

static void
grl_dleyna_manager_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
grl_dleyna_manager_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
grl_dleyna_manager_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_grl_dleyna_manager_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GRL_DLEYNA_TYPE_MANAGER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GRL_DLEYNA_TYPE_MANAGER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
grl_dleyna_manager_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  GrlDleynaManagerProxy *proxy = GRL_DLEYNA_MANAGER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_grl_dleyna_manager_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_grl_dleyna_manager_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
grl_dleyna_manager_proxy_init (GrlDleynaManagerProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = grl_dleyna_manager_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GRL_DLEYNA_TYPE_MANAGER_PROXY, GrlDleynaManagerProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), grl_dleyna_manager_interface_info ());
}

static void
grl_dleyna_manager_proxy_class_init (GrlDleynaManagerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = grl_dleyna_manager_proxy_finalize;
  gobject_class->get_property = grl_dleyna_manager_proxy_get_property;
  gobject_class->set_property = grl_dleyna_manager_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = grl_dleyna_manager_proxy_g_signal;
  proxy_class->g_properties_changed = grl_dleyna_manager_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GrlDleynaManagerProxyPrivate));
#endif
}

static void
grl_dleyna_manager_proxy_iface_init (GrlDleynaManagerIface *iface)
{
}

/**
 * grl_dleyna_manager_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-intel-dLeynaServer-Manager.top_of_page">com.intel.dLeynaServer.Manager</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call grl_dleyna_manager_proxy_new_finish() to get the result of the operation.
 *
 * See grl_dleyna_manager_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
grl_dleyna_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GRL_DLEYNA_TYPE_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.intel.dLeynaServer.Manager", NULL);
}

/**
 * grl_dleyna_manager_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to grl_dleyna_manager_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with grl_dleyna_manager_proxy_new().
 *
 * Returns: (transfer full) (type GrlDleynaManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
GrlDleynaManager *
grl_dleyna_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GRL_DLEYNA_MANAGER (ret);
  else
    return NULL;
}

/**
 * grl_dleyna_manager_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-intel-dLeynaServer-Manager.top_of_page">com.intel.dLeynaServer.Manager</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See grl_dleyna_manager_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GrlDleynaManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
GrlDleynaManager *
grl_dleyna_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GRL_DLEYNA_TYPE_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.intel.dLeynaServer.Manager", NULL);
  if (ret != NULL)
    return GRL_DLEYNA_MANAGER (ret);
  else
    return NULL;
}


/**
 * grl_dleyna_manager_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like grl_dleyna_manager_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call grl_dleyna_manager_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See grl_dleyna_manager_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
grl_dleyna_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GRL_DLEYNA_TYPE_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.intel.dLeynaServer.Manager", NULL);
}

/**
 * grl_dleyna_manager_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to grl_dleyna_manager_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with grl_dleyna_manager_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type GrlDleynaManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
GrlDleynaManager *
grl_dleyna_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GRL_DLEYNA_MANAGER (ret);
  else
    return NULL;
}

/**
 * grl_dleyna_manager_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like grl_dleyna_manager_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See grl_dleyna_manager_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GrlDleynaManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
GrlDleynaManager *
grl_dleyna_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GRL_DLEYNA_TYPE_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.intel.dLeynaServer.Manager", NULL);
  if (ret != NULL)
    return GRL_DLEYNA_MANAGER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * GrlDleynaManagerSkeleton:
 *
 * The #GrlDleynaManagerSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GrlDleynaManagerSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GrlDleynaManagerSkeleton.
 */

struct _GrlDleynaManagerSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_grl_dleyna_manager_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  GrlDleynaManagerSkeleton *skeleton = GRL_DLEYNA_MANAGER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GRL_DLEYNA_TYPE_MANAGER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GRL_DLEYNA_TYPE_MANAGER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_grl_dleyna_manager_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  GrlDleynaManagerSkeleton *skeleton = GRL_DLEYNA_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_grl_dleyna_manager_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_grl_dleyna_manager_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  GrlDleynaManagerSkeleton *skeleton = GRL_DLEYNA_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_grl_dleyna_manager_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _grl_dleyna_manager_skeleton_vtable =
{
  _grl_dleyna_manager_skeleton_handle_method_call,
  _grl_dleyna_manager_skeleton_handle_get_property,
  _grl_dleyna_manager_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
grl_dleyna_manager_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return grl_dleyna_manager_interface_info ();
}

static GDBusInterfaceVTable *
grl_dleyna_manager_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_grl_dleyna_manager_skeleton_vtable;
}

static GVariant *
grl_dleyna_manager_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  GrlDleynaManagerSkeleton *skeleton = GRL_DLEYNA_MANAGER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_grl_dleyna_manager_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _grl_dleyna_manager_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _grl_dleyna_manager_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _grl_dleyna_manager_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.intel.dLeynaServer.Manager", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
grl_dleyna_manager_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_grl_dleyna_manager_on_signal_found_server (
    GrlDleynaManager *object,
    const gchar *arg_Path)
{
  GrlDleynaManagerSkeleton *skeleton = GRL_DLEYNA_MANAGER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_Path));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.intel.dLeynaServer.Manager", "FoundServer",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_grl_dleyna_manager_on_signal_lost_server (
    GrlDleynaManager *object,
    const gchar *arg_Path)
{
  GrlDleynaManagerSkeleton *skeleton = GRL_DLEYNA_MANAGER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_Path));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.intel.dLeynaServer.Manager", "LostServer",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void grl_dleyna_manager_skeleton_iface_init (GrlDleynaManagerIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GrlDleynaManagerSkeleton, grl_dleyna_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (GrlDleynaManagerSkeleton)
                         G_IMPLEMENT_INTERFACE (GRL_DLEYNA_TYPE_MANAGER, grl_dleyna_manager_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (GrlDleynaManagerSkeleton, grl_dleyna_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GRL_DLEYNA_TYPE_MANAGER, grl_dleyna_manager_skeleton_iface_init))

#endif
static void
grl_dleyna_manager_skeleton_finalize (GObject *object)
{
  GrlDleynaManagerSkeleton *skeleton = GRL_DLEYNA_MANAGER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (grl_dleyna_manager_skeleton_parent_class)->finalize (object);
}

static void
grl_dleyna_manager_skeleton_init (GrlDleynaManagerSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = grl_dleyna_manager_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GRL_DLEYNA_TYPE_MANAGER_SKELETON, GrlDleynaManagerSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
grl_dleyna_manager_skeleton_class_init (GrlDleynaManagerSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = grl_dleyna_manager_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = grl_dleyna_manager_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = grl_dleyna_manager_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = grl_dleyna_manager_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = grl_dleyna_manager_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GrlDleynaManagerSkeletonPrivate));
#endif
}

static void
grl_dleyna_manager_skeleton_iface_init (GrlDleynaManagerIface *iface)
{
  iface->found_server = _grl_dleyna_manager_on_signal_found_server;
  iface->lost_server = _grl_dleyna_manager_on_signal_lost_server;
}

/**
 * grl_dleyna_manager_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-intel-dLeynaServer-Manager.top_of_page">com.intel.dLeynaServer.Manager</link>.
 *
 * Returns: (transfer full) (type GrlDleynaManagerSkeleton): The skeleton object.
 */
GrlDleynaManager *
grl_dleyna_manager_skeleton_new (void)
{
  return GRL_DLEYNA_MANAGER (g_object_new (GRL_DLEYNA_TYPE_MANAGER_SKELETON, NULL));
}

